import type { Metadata } from "next";
import { Poppins } from "next/font/google"; // Import Poppins from next/font/google
import "./globals.css";
import Header from "../app/components/Header";
import Footer from "../app/components/Footer";
import { MyProvider } from "./context/MyContext"; // Import the context provider

const poppins = Poppins({
  subsets: ["latin"], // Specify the subset (e.g., latin)
  weight: ["400", "600", "700"], // Use specific weights as needed
  variable: "--font-poppins", // Optional CSS variable
});

export const metadata: Metadata = {
  title: "VALLUM CAPITAL ADVISORS-SEBI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <MyProvider> {/* Wrap with the provider */}
          <Header />
          {children}  
          <section className="bg-purple-950 text-center py-16">
            <h2 className="text-white text-lg md:text-xl font-medium mb-6">
              SEBI PMS Registration no. INP000007650
            </h2>

        
            <a href="/getintouch"><button className="max-w-48 mt-4 px-4 py-2 bg-white text-purple-950 font-semibold hover:bg-purple-950 hover:text-white shadow hover:border-solid hover:border hover:border-black">Get In Touch</button></a>
          </section>
          <Footer />
        </MyProvider>
      </body>
    </html>
  );
}
